### ISSUE TITLE
Some stuff

### ISSUE THREAD

**Issue by jfceja** [PenguinGovernor/c_vector_lib#1]
https://github.com/PenguinGovernor/c_vector_lib/blob/83cfb52bd79328380540020d8a739cf347c95c64/vector.c#L52  
What if the index is out of bounds?
https://github.com/PenguinGovernor/c_vector_lib/blob/83cfb52bd79328380540020d8a739cf347c95c64/vector.c#L87
Why not just set the newVector's length to pVec's current length + 1?  On line 93 the size will double since it reached its max capacity and may double several more times as the rest of the items gets added to the new vector, it seems faster to just allocate the sufficient amount of space from the very beginning?
https://github.com/PenguinGovernor/c_vector_lib/blob/83cfb52bd79328380540020d8a739cf347c95c64/vector.c#L96
Similar to line 52, what if the index is out of bounds? I think both this function and vectorAdd should check for out of bounds rather than vectorInsertAt relying on vectorAdd's check.
https://github.com/PenguinGovernor/c_vector_lib/blob/83cfb52bd79328380540020d8a739cf347c95c64/vector.c#L141
Should be pVecB not pVecA?

**Comment by penguingovernor** [comment]
All of these issues should be addressed in the last five commits: <br>

1. ae8114a7b86b9b5d6e35ee4a4f3f242aa3331638
2. 9661c3a955cb100fe7fe21511d4c4d486c7e8775
3. fa129a8d73ffc3de4a499a81bf6c4841cb026d06
4. cc893fe7a8412e2e6e3bd4df178f26dd8f9d09e8
5. 4782deb5bf9e7b3a58bf3b8d6e9e61e7a9bbb3a2

The only thing I would have a question on is how vectorAdd would implement index checking since it doesn't take in an index and relies solely on it's interal struct members to add the item?

**Comment by jfceja** [comment]
I think I meant to say the functions vectorInsertAt and vectorGet instead of vectorInsertAt and vectorAdd. Your recent commits seem to have index checking on these functions now, so 👍
